[envs.test]
dependencies = [
  "coverage[toml]>=6.5",
  "mock",
  "pytest",
  "pytest-cov",
]
# Install all optional dependencies.
features = [
    "api",
    "bigquery",
    "cloud_monitoring",
    "cloud_service_monitoring",
    "cloud_storage",
    "cloudevent",
    "datadog",
    "dynatrace",
    "elasticsearch",
    "opensearch",
    "prometheus",
    "pubsub",
    "splunk",
]
[envs.test.scripts]
#TODO: Check what coverage does exactly, and if there is a more modern approach, for example with `py-cov`.
unit = "pytest --cov=coverage {args:tests} -p no:warnings"
cov = "coverage report --rcfile='.coveragerc'"

[envs.lint]
detached = true
dependencies = [
  "black>=24.3.0", # avoid CVE-2024-21503 (reported by `safety check`)
  "mypy",
  "ruff",
]
[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/slo_generator}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  #FIXME Configure `mypy` from `pyproject.toml`, like `pytype`. 
  "style",
]
all = [
  "style",
  "typing",
]

[envs.audit]
detached = true
dependencies = [
    "bandit",
    "safety",
]
[envs.audit.scripts]
all = [
    "bandit -c pyproject.toml -r .",
    # Ignore CVE-2018-20225 with Vulnerability ID 67599.
    # We do not use the `--extra-index-url` option, and the behavior is intended anyway.
    "safety check --ignore 67599",
]
