name: Continuous Integration

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
      - name: Set up pip cache
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip- 
      - name: Install Hatch
        run: pipx install hatch
      - name: Run unit tests with coverage
        run: hatch run test:unit-cov
        env:
          MIN_VALID_EVENTS: 10
          GOOGLE_APPLICATION_CREDENTIALS: tests/unit/fixtures/fake_credentials.json
      - name: Lint
        run: hatch run lint:all
      - name: Audit
        run: hatch run audit:all
      - name: Build
        run: hatch build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master

      - name: Build Docker image
        run: make docker_build
